version: "3"

services:
  database:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./init-mongo:/docker-entrypoint-initdb.d

  next:
    build: .
    image: next-news-app
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - database
    environment:
      DB_URL: mongodb://database:27017/next-news

  storybook:
    build: .
    image: next-next-storybook
    init: true
    command: npm run storybook
    ports:
      - 6006:6006
    volumes:
      - .:/app
